---
title: "Stemma Regimiento"
author: "MGL"
date: "2023"
output:
  html_document:
    toc: true
    number_sections: true
  pdf_document:
    toc: true
    number_sections: true
---
#abstract: "À partir du script de JB Camps et du travail d'Ariane Pinche"
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Construction du stemma du *Regimiento*

```{r}
# Load data
Regimiento = read.csv(file = "../data/stemma_filtre.csv", header = TRUE, row.names = 1, sep=",")
RegimientoMatrix = as.matrix(Regimiento)
# Ordre des témoins alphabétique 
# A B G J Q R Z U 
# Load package
library(stemmatology)
#cite("stemmatology")
#vignette("stemmatology")
```


### AGJZ
```{r}
# A B G J Q R Z U 
# Il faut faire attention au changement d'ordre après la suppression de chaque colonne
Regimiento_brancheB = RegimientoMatrix[,-2]
Regimiento_brancheB = Regimiento_brancheB[, -4]
Regimiento_brancheB = Regimiento_brancheB[, -4]
Regimiento_brancheB = Regimiento_brancheB[, -5]
# On supprime J
#Regimiento_brancheB = Regimiento_brancheB[, -3]
# print(Regimiento_brancheB)
PCC(Regimiento_brancheB, ask=FALSE, threshold=0.35, omissionsAsReadings=FALSE)
```
